### ISSUE TITLE
[RFC] Roadmap for v3

### ISSUE THREAD

**Issue by Dragon-Fish** [genshin-kit/genshin-kit-node#85]
GenshinKit v2 是用 TypeScript 基于 v1 的屎山代码重构的，虽然有了 types 支持，但是很多代码的逻辑因为技术债务事实上非常魔幻。

因此计划在近期进行一些逻辑重构和规范化。

**本次更新将会是 major 更新，意味着大部分接口很可能不向前兼容。**

## 拆分

- [ ] 将 `getDS` 拆分为独立包 `@genshin-kit/dynamic-secret`，版本号与米游社 App 同步（该包将作为官方 DS 生成器，这意味着将会支持用户自定义 DS 生成器以应对 mhy 突发更新）

## 命名规范

- [ ] 将模块文件夹重命名为复数形式（`util` → `utils`）
- [ ] 使用 ES6 setter getter 取代 `setCookie` 等方法，这样校验数据更方便，逻辑也更清晰
- [ ] 抛弃 `getXxx` `setXxx` 的命名方法， `getUserRoles` → `userRoles` （事实上 util.CharactersFilter 就遵守该命名规范）
- [ ] 使用 `#` 字面量重命名私有变量，规范原有的 `_` 开头的变量与方法
